### ISSUE TITLE
feat(database): allow templating of images

### ISSUE THREAD

**Issue by eladzlot** [minnojs/minno-time#42]
If templates are used within images they are preloaded incorrectly.
We can't template the image names at pre-load because they may be decided dynamically.
The solution is to
- allow preloading from the API and/or piManager. (maybe allow preloading a global/current template as well?).
- preload all external content imidiately pre-trial, just to be sure that all media is available. The nice thing about this approach is that many times it will be faster.

**Comment by eladzlot** [comment]
This has some structural implications for PIP. In particular for trial instantiation.

**Comment by baranan** [comment]
Wouldn't preload pre-trial slow PIP down? We need trials to start immediately after the previous trial ends. 


Isn't it possible simply not to preload images that have <% in their path? My problem was that the task completely broke. It would have been better if the problem was that PIP failed to preload the image, but the problem was that PIP simply broke.

**Comment by eladzlot** [comment]
If images have already been preloaded, then pre-loading them again should me a matter of milliseconds.
If they haven't been preloaded, then it is imperative that we pre-load them, otherwise all timing is completely unreliable.

**Comment by baranan** [comment]
A matter of how many milliseconds? I'm concerned about the risk. 

I think that we can recommend programmers to use a preload function in the manager's script that will activate the preload right at the beginning of the study. That, in addition to a preload in PIP should be good enough. But, if PIP cannot handle, in the preload, templated file paths, then it will be ideal if PIP does not break when the image is not found (at least when the file path includes <%).

**Comment by eladzlot** [comment]
A few milliseconds (1-3 I guess). Although, the timing between tasks is not very tight as is. It takes about 20ms to load a preloaded image in the first place.

I don't think we can afford to leave this issue up to the users. If a user forgets to preload an image. Or skips preloading altogether, then all measures that have to do with that trial (or trials) is meaningless.

**Comment by baranan** [comment]
I'm suggesting to leave it up to the users only in the cases they use a template for the file name (assuming that it is really impossible to resolve the template).


The fact that it takes about 20ms to load each image is concerning. Does it mean that if I set a 250ms between trials (by adding a blank screen for 250ms at the end of each trial), the inter-trial-interval is actually 250+(20*number-of-images)?

**Comment by eladzlot** [comment]
I'm guessing there is a constant 10ms to 30ms between trails. multiple
images would be loaded in parallel. We can improve this delay by a little
bit although it necessarily takes time to set up a trial.

We should discuss this in person.
There is a mix of technological and UI problems here.

**Comment by eladzlot** [comment]
I'm closing this for now.
We can't afford to space out the trails because we need the layout to seem continuous to users.
(btw right now we have 3-4ms between trials)
