### ISSUE TITLE
Warning: Required config property "watch.user.files" missing.

### ISSUE THREAD

**Issue by nipunsadvilkar** [minnojs/minno-time#56]
I installed minno-time on my local machine (Ubuntu x64) as per documentation on following website:
https://minnojs.github.io/minno-time/0.3/time/install.html

But when I do `npm start` on terminal, it opens blank web browser and nothing happens whereas in documentation they have mentioned:

> You will find that a browser window opens with the tutorials site, only this time from your local machine.

I don't see any tutorial site and terminal is constantly raising :

```
Running "watch:user" (watch) task
Waiting...
Verifying property watch.user.files exists in config...ERROR
>> Unable to process task.
Warning: Required config property "watch.user.files" missing.
```

until I press Ctrl + C.

I am using NodeJS LTS version (v6.10.0).

Inputs to resolve above errors would be very helpful!

**Comment by eladzlot** [comment]
Hi @nipunsadvilkar you can update (and `npm install`) and it should work for you now.
We do most of our testing in the documentation site (see [here](https://minnojs.github.io/minno-time/0.3/time/helloPlay.html) or [here](https://minnojs.github.io/minno-time/0.3/time/iat.html)) for example.

If you run into further problems, please let us know.

**Comment by nipunsadvilkar** [comment]
@eladzlot : Thanks for helping. Issue got resolved.
Btw, I am new to NodeJS but curious to know what was wrong with the previous code. I have through your commit..looks like you replaced `grunt server` with `http server`. still would like to know more about it

**Comment by eladzlot** [comment]
Hi @nipunsadvilkar,
We used to have quite a complex server setup using [expressjs](https://expressjs.com/) that was activated using [grunt](https://gruntjs.com/). Since we have live parsing of tasks on the documentation site we gave up on its maintenance and we can downgrade to a simple [http-server](https://www.npmjs.com/package/http-server).
