### ISSUE TITLE
Improve duration property for the trigger action

### ISSUE THREAD

**Issue by baranan** [minnojs/minno-time#59]
It seems that the 'duration' property in a timeout input is more advanced than the 'duration' property for a 'trigger' action. Timeout's duration supports the following options, not supported by the trigger's duration property:
![image](https://user-images.githubusercontent.com/4257111/29971455-f5f59a4e-8f30-11e7-9d6a-82d6d1f2452d.png)

**Comment by eladzlot** [comment]
They are already the same. I'll update the docs.

**Comment by baranan** [comment]
I thought I found out they are not when {min max} did not work for me with a trigger, but perhaps the problem was different.
