### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by natashamaniar** [minnojs/minno-time#68]
for logging into a csv, what should the url be? I'm not able to write to the results folder

**Comment by eladzlot** [comment]
Hi @natashamaniar,  the correct place to ask this is at the MinnoJS google group: https://groups.google.com/u/2/g/minnojs
Or maybe on the simple-server issues https://github.com/minnojs/simple-minno-server

At any rate, MinnoJS posts the CSV to the url you set.
If you are using the simple-minno-server, then the url should be the csv.php file (and see the example provider there).
If you are hosting your own solution then you should consult your IT people regarding where to send the data.
